### ISSUE TITLE
Installs in custom_components/custom_components directory

### ISSUE THREAD

**Issue by i-am-snappy** [atymic/project_three_zero_ha#1]
I've just noticed that the component installs in custom_components/custom_components/project_zero_three directory instead of in custom_components/project_zero_three.. (whatever it is supposed to be)

I was wondering where my custom_components folder was going when I uninstalled this integration.

the uninstall was removing the whole custom_components folder.

BTW - I run Hassio (homeassistant) and used HACS to install.

**Comment by i-am-snappy** [comment]
further to this i notice the hacs.json and README.md are in the top level custom_components folder

**Comment by atymic** [comment]
Hey. I had a look and I think this was due to setting the `content_in_root` flag.
https://github.com/atymic/project_three_zero_ha/commit/d00cfa60b38240dbed6a256cfdde36c2fd14ddd8

Let me know if that fixes it for you :)

**Comment by i-am-snappy** [comment]
Yep that did the trick. Thanks.
I'm in WA - how can I get the sensors to show around here - I see NSW, VIC and QLD

**Comment by atymic** [comment]
So the way this works is people generally mock their location to get the cheapest price wherever it is in aus :)
See: https://www.ozbargain.com.au/node/288802
