### ISSUE TITLE
Region Specific Output

### ISSUE THREAD

**Issue by boomyville** [atymic/project_three_zero_ha#2]
Maybe add to readme that you can change the region which information is displayed from

You currently have self._data = res.json()['regions'][0]['prices'] in sensor.py
Changing [0] to [1] for example will only spit out VIC locations
NSW would be [2], QLD [3], WA [4]

Anyway great job with this integration!

**Comment by atymic** [comment]
`['regions'][0]` is actually the region `All`, and is the one you generally want (since any petrol station is fine using your helicopter 😉 )

That being said making it configable can't hurt, so happy to accept a PR :)
