### ISSUE TITLE
No 'version' key in the manifest.json

### ISSUE THREAD

**Issue by kaizersoje** [atymic/project_three_zero_ha#3]
Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

There is an error message in the logs that says -

`As of Home Assistant 2021.6, this integration will no longer be loaded.`

**Comment by atymic** [comment]
I haven't touched this in a while and don't really run HA anymore. Feel free to PR a fix :)

**Comment by atymic** [comment]
Closed in #4
