### ISSUE TITLE
Lat/Long suggestions

### ISSUE THREAD

**Issue by hiraniha** [atymic/project_three_zero_ha#5]
Hi I have some slight suggestions

1) the lat/long to be swapped over to match the input for the 3uTools
2) the lat /long values were showing more that 6 decimal places in HA and couldn't be pasted to the u3Tools

I have updated my sensor.py so it now looks like this by swapping the two lines and adding a round(x,6)

`        return {`
`            ATTR_ATTRIBUTION: ATTRIBUTION,`
`            ATTR_LONGITUDE: round(data['lng'],6) or None,`
`            ATTR_LATITUDE: round(data['lat'],6) or None`
`        }`

![image](https://user-images.githubusercontent.com/73940881/143662460-ebd7c7a3-33ff-417a-9c37-03e50e5e1dda.png)

![image](https://user-images.githubusercontent.com/73940881/143662434-f599ca71-a531-48b5-92ae-aa1ae515c9c5.png)

**Comment by atymic** [comment]
I don't actually use this anymore but feel free to PR :)
